partA

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 100)

In [3]:
df_price = pd.read_csv('data_export/data_us/adjusted.csv',parse_dates=['Date'])
df_tickers = pd.read_csv('data_export/data_us/tickers.csv',names=['ticker','GISC code'])
df_univ = pd.read_csv('data_export/data_us/univ_h.csv')

In [4]:
df_tickers['industry'] = df_tickers.iloc[:,1].astype(str).str[:6]
df_tickers = df_tickers.dropna(subset=['GISC code'])
#drop goog and nws
df_tickers.drop(df_tickers[(df_tickers['ticker']=='GOOG') | (df_tickers['ticker']=='NWS')].index,inplace=True)
#drop '#N/A Invalid Security' row
df_tickers = df_tickers[df_tickers['GISC code'] != '#N/A Invalid Security']
df_tickers

       ticker GISC code industry
9    0910150D  25301020   253010
19   1284849D  35202010   352020
20   1288453D  30201030   302010
27   1448062D  50201030   502010
28   1500785D  55103010   551030
..        ...       ...      ...
959       YUM  25301040   253010
960       ZBH  35101010   351010
961      ZBRA  45203010   452030
962      ZION  40101015   401010
963       ZTS  35202010   352020

[781 rows x 3 columns]

In [5]:
df_price = df_price.set_index('Date')
df_log_return = np.log(df_price / df_price.shift(1)).replace([np.inf, -np.inf], np.nan)

# df_log_return = df_log_return.iloc[1:]
df_log_return = df_log_return.fillna(0)
df_log_return

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2004-01-05,0.005072,0.001627,0.036087,-0.017489,0.018884,0.000720,0.071045,0.040209,0.0,0.009351,...,0.023112,-0.016705,0.016778,0.008126,0.000000,0.014501,-0.009040,0.001834,-0.002162,0.000000
2004-01-06,0.001685,-0.013090,0.017325,0.026073,0.023216,-0.000720,-0.004425,0.039217,0.0,0.001161,...,-0.006754,0.001594,0.017932,-0.019181,0.000000,0.029540,-0.004914,0.002287,0.013722,0.000000
2004-01-07,-0.010152,0.020725,-0.015079,-0.004761,-0.001425,-0.008668,-0.013423,-0.013092,0.0,-0.018177,...,-0.007293,-0.005240,0.003544,-0.004672,0.000000,-0.017267,0.011092,0.016616,-0.006920,0.000000
2004-01-08,-0.006826,0.004599,0.045047,-0.053103,-0.001832,-0.000726,0.017848,0.014223,0.0,0.012935,...,-0.002443,0.006372,0.002829,0.006825,0.000000,0.002905,0.019157,0.002245,0.005277,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,-0.001676,0.012556,0.004024,0.000000,0.000793,-0.001360,0.008906,-0.003491,0.004882,0.015661
2025-12-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,-0.000923,0.040750,0.000000,0.000000,0.000504,-0.007023,0.005967,0.001504,-0.000672,0.005880
2025-12-29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.011851,-0.023717,-0.016196,0.000000,-0.002814,-0.006350,-0.002648,-0.002154,-0.011492,-0.001982
2025-12-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.003809,0.013245,0.012172,0.000000,-0.005942,-0.000591,0.005522,0.004061,-0.002212,0.003407
2025-12-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,-0.005387,0.002628,-0.035237,0.000000,-0.010301,-0.005932,-0.009629,-0.016015,-0.002729,-0.004678

In [6]:
#calculate 5-day log return
df_ret_5d = np.log(df_price / df_price.shift(5)).replace([np.inf, -np.inf], np.nan)
# df_ret_5d = df_ret_5d.iloc[5:]
#fillna with 0
df_ret_5d = df_ret_5d.fillna(0)
df_ret_5d.head(10)

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
2004-01-05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
2004-01-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
2004-01-07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
2004-01-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
2004-01-09,-0.004246,-0.006769,0.075014,-0.026203,0.047163,-0.010121,0.041867,0.080557,0.0,-0.005888,...,-0.008401,-0.015795,0.026862,0.021053,0.0,0.018323,0.012069,0.015481,-0.002829,0.0
2004-01-12,-0.024324,0.008786,0.073146,-0.021578,0.023621,-0.011568,-0.031454,0.068209,0.0,-0.015829,...,-0.017468,-0.010525,0.015085,0.023635,0.0,0.014019,0.021109,0.021148,-0.009870,0.0
2004-01-13,-0.042999,0.015178,0.023278,-0.063616,0.001625,-0.021081,-0.057153,0.044255,0.0,-0.012861,...,-0.015131,-0.021827,-0.023009,0.028978,0.0,-0.025429,0.013381,0.026306,-0.034582,0.0
2004-01-14,-0.020185,0.016458,0.015079,-0.048385,0.001223,-0.008016,-0.029712,0.078762,0.0,0.007078,...,-0.007838,-0.022415,-0.026553,0.018915,0.0,0.004634,0.003005,0.003887,-0.024945,0.0
2004-01-15,-0.013793,0.020661,-0.019960,0.009814,-0.013123,-0.015369,-0.068678,0.049601,0.0,-0.013526,...,-0.015275,-0.028788,-0.034486,-0.025735,0.0,0.001443,-0.006911,-0.013697,-0.020942,0.0

In [7]:
#compute 21-day rolling volatility
df_rolling_vol = df_log_return.rolling(window=21,min_periods=5).std()
# df_rolling_vol = df_rolling_vol.loc[df_ret_5d.index]
# df_rolling_vol = df_rolling_vol[4:]
#set the floor of volatility to 0.003
df_rolling_vol = df_rolling_vol.clip(lower=0.003)
df_rolling_vol.head(10)

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-08,0.006272,0.012106,0.024843,0.028907,0.012240,0.003842,0.033750,0.023614,0.003,0.012051,...,0.012552,0.008812,0.008457,0.011028,0.003,0.017417,0.011649,0.006784,0.007890,0.003
2004-01-09,0.006495,0.014440,0.024459,0.029142,0.010950,0.003468,0.035000,0.022122,0.003,0.011876,...,0.013061,0.007891,0.011880,0.016284,0.003,0.017103,0.010858,0.007824,0.009271,0.003
2004-01-12,0.008022,0.014888,0.023789,0.026796,0.011059,0.003187,0.032141,0.020918,0.003,0.010842,...,0.013275,0.007935,0.010846,0.015112,0.003,0.015844,0.009941,0.007380,0.009084,0.003
2004-01-13,0.008973,0.014084,0.027836,0.025079,0.010382,0.004258,0.032334,0.019367,0.003,0.010196,...,0.012428,0.007629,0.013311,0.015426,0.003,0.015479,0.010512,0.006989,0.009027,0.003
2004-01-14,0.010163,0.015004,0.028249,0.024161,0.010011,0.004621,0.030547,0.018224,0.003,0.009562,...,0.011626,0.007148,0.012461,0.015500,0.003,0.014894,0.009837,0.007280,0.008647,0.003
2004-01-15,0.009607,0.014270,0.026664,0.023000,0.011510,0.004781,0.029761,0.019791,0.003,0.009330,...,0.011409,0.006904,0.011922,0.018956,0.003,0.014093,0.009722,0.008932,0.008932,0.003

In [8]:
print(df_ret_5d.shape)
print(df_rolling_vol.shape)

print(df_ret_5d.index.equals(df_rolling_vol.index))
print(df_ret_5d.columns.equals(df_rolling_vol.columns))

(5535, 964)
(5535, 964)
True
True

In [10]:
df_ret_5d_nml = df_ret_5d.div(df_rolling_vol)
df_ret_5d_nml = df_ret_5d_nml[5:]
df_ret_5d_nml.head(10)

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-09,-0.653777,-0.468735,3.066892,-0.899135,4.307232,-2.918108,1.196199,3.641529,0.0,-0.495747,...,-0.643227,-2.001556,2.261148,1.292859,0.0,1.071378,1.111490,1.978695,-0.305080,0.0
2004-01-12,-3.031990,0.590145,3.074761,-0.805264,2.135838,-3.629962,-0.978617,3.260727,0.0,-1.459878,...,-1.315858,-1.326412,1.390744,1.563981,0.0,0.884815,2.123412,2.865506,-1.086509,0.0
2004-01-13,-4.792129,1.077675,0.836267,-2.536642,0.156500,-4.951184,-1.767577,2.285132,0.0,-1.261354,...,-1.217436,-2.861092,-1.728587,1.878499,0.0,-1.642727,1.272969,3.763675,-3.831075,0.0
2004-01-14,-1.986168,1.096866,0.533804,-2.002560,0.122141,-1.734462,-0.972648,4.321815,0.0,0.740245,...,-0.674191,-3.136095,-2.130928,1.220349,0.0,0.311116,0.305502,0.533898,-2.884743,0.0
2004-01-15,-1.435811,1.447852,-0.748572,0.426684,-1.140145,-3.214480,-2.307600,2.506188,0.0,-1.449666,...,-1.338795,-4.169559,-2.892749,-1.357650,0.0,0.102405,-0.710899,-1.533427,-2.344679,0.0
2004-01-16,-2.162302,1.540993,0.066063,-0.132808,-0.433245,-4.859327,-1.059391,3.179536,0.0,-1.109804,...,0.472955,-2.926703,-2.688451,-3.912832,0.0,0.491686,2.991951,1.240651,0.323735,0.0
2004-01-20,-0.895110,-0.142199,-1.965658,-0.195357,1.682283,-4.569014,-0.591639,1.138068,0.0,-1.164190,...,0.045154,-2.543938,-3.800638,-2.288295,0.0,-0.661967,1.897288,1.160609,2.656212,0.0
2004-01-21,2.087412,2.505215,-1.904824,2.747203,2.391178,-3.096340,1.946994,0.644877,0.0,0.675722,...,1.664930,-0.158190,-0.416308,-1.643654,0.0,1.480937,2.811027,-1.417720,4.972435,0.0
2004-01-22,0.947359,1.186810,-2.533958,3.095886,1.796939,-3.936548,0.000000,-1.097915,0.0,-0.230337,...,1.377467,1.404968,-2.016541,-1.583834,0.0,0.576360,2.895562,-0.999883,2.109082,0.0
2004-01-23,2.396684,0.884220,-2.988150,3.113451,4.056507,-1.740343,0.897450,-0.060191,0.0,-0.059355,...,1.796950,1.606888,-0.269433,0.389566,0.0,1.097766,2.481064,1.131642,2.225753,0.0

In [11]:
# extract ticker list of each year from df_univ
df_univ = df_univ.set_index('year')
univ_dict = {
    year: df_univ.columns[df_univ.loc[year] == 1].tolist()
    for year in df_univ.index
}

In [12]:
# create a mask with same size as df_ret_5d_nml
df_ret_5d_nml.columns = df_ret_5d_nml.columns.str.strip()

mask = pd.DataFrame(
    False,
    index=df_ret_5d_nml.index,
    columns=df_ret_5d_nml.columns
)

for year, tickers in univ_dict.items():
    year_rows = df_ret_5d_nml.index.year == year
    valid_cols = [t for t in tickers if t in df_ret_5d_nml.columns]
    mask.loc[year_rows, valid_cols] = True

# apply the mask on df_ret_5d_nml，assign np.nan to values not in the universe
df_ret_filtered = df_ret_5d_nml.where(mask,np.nan)
df_ret_filtered

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-09,-0.653777,-0.468735,3.066892,-0.899135,4.307232,NaN,1.196199,3.641529,NaN,-0.495747,...,-0.643227,NaN,2.261148,NaN,NaN,1.071378,1.111490,NaN,-0.305080,NaN
2004-01-12,-3.031990,0.590145,3.074761,-0.805264,2.135838,NaN,-0.978617,3.260727,NaN,-1.459878,...,-1.315858,NaN,1.390744,NaN,NaN,0.884815,2.123412,NaN,-1.086509,NaN
2004-01-13,-4.792129,1.077675,0.836267,-2.536642,0.156500,NaN,-1.767577,2.285132,NaN,-1.261354,...,-1.217436,NaN,-1.728587,NaN,NaN,-1.642727,1.272969,NaN,-3.831075,NaN
2004-01-14,-1.986168,1.096866,0.533804,-2.002560,0.122141,NaN,-0.972648,4.321815,NaN,0.740245,...,-0.674191,NaN,-2.130928,NaN,NaN,0.311116,0.305502,NaN,-2.884743,NaN
2004-01-15,-1.435811,1.447852,-0.748572,0.426684,-1.140145,NaN,-2.307600,2.506188,NaN,-1.449666,...,-1.338795,NaN,-2.892749,NaN,NaN,0.102405,-0.710899,NaN,-2.344679,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.231002,NaN,NaN,NaN,1.554232,0.545711,-1.045524,-2.346002,NaN,1.645847
2025-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.814036,NaN,NaN,NaN,1.773551,-0.699833,0.372041,-2.010426,NaN,2.108285
2025-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.649493,NaN,NaN,NaN,0.284738,-0.710271,1.439875,-1.858874,NaN,2.279093
2025-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.962851,NaN,NaN,NaN,-1.263642,-1.478724,1.239770,-0.841976,NaN,1.590818
2025-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.630714,NaN,NaN,NaN,-2.027623,-1.620455,0.858266,-1.236315,NaN,1.389272

In [13]:
#convert to long format
df_5d_ret_long = (
    df_ret_filtered
    .stack(dropna=False)
    .reset_index()
)

df_5d_ret_long.columns = ['date', 'ticker', '5d_ret']
df_5d_ret_long

              date    ticker    5d_ret
0       2004-01-09  0111145D -0.653777
1       2004-01-09  0202445Q -0.468735
2       2004-01-09  0203524D  3.066892
3       2004-01-09  0226226D -0.899135
4       2004-01-09  0544749D  4.307232
...            ...       ...       ...
5330915 2025-12-31       YUM -1.620455
5330916 2025-12-31       ZBH  0.858266
5330917 2025-12-31      ZBRA -1.236315
5330918 2025-12-31      ZION       NaN
5330919 2025-12-31       ZTS  1.389272

[5330920 rows x 3 columns]

In [14]:
#merge with industry code
df_5d_ret_long = df_5d_ret_long.merge(df_tickers[['ticker', 'industry']], on='ticker', how='left')
df_5d_ret_long

              date    ticker    5d_ret industry
0       2004-01-09  0111145D -0.653777      NaN
1       2004-01-09  0202445Q -0.468735      NaN
2       2004-01-09  0203524D  3.066892      NaN
3       2004-01-09  0226226D -0.899135      NaN
4       2004-01-09  0544749D  4.307232      NaN
...            ...       ...       ...      ...
5330915 2025-12-31       YUM -1.620455   253010
5330916 2025-12-31       ZBH  0.858266   351010
5330917 2025-12-31      ZBRA -1.236315   452030
5330918 2025-12-31      ZION       NaN   401010
5330919 2025-12-31       ZTS  1.389272   352020

[5330920 rows x 4 columns]

In [15]:
#calculate industry average for variable (prior 5-day return)  
df_industry_5d_ret = (
    df_5d_ret_long
    .dropna(subset=['industry']) 
    .groupby(['date', 'industry'])['5d_ret']
    .mean()
    .reset_index()
)
df_industry_5d_ret.rename(columns={'5d_ret': 'industry_5d_ret'}, inplace=True)
df_industry_5d_ret

             date industry  industry_5d_ret
0      2004-01-09   101010         2.532214
1      2004-01-09   101020         2.007637
2      2004-01-09   151010        -0.515958
3      2004-01-09   151020         1.518106
4      2004-01-09   151030         0.334944
...           ...      ...              ...
387095 2025-12-31   601050         0.100130
387096 2025-12-31   601060         1.582779
387097 2025-12-31   601070        -0.006499
387098 2025-12-31   601080         0.921591
387099 2025-12-31   602010        -0.536621

[387100 rows x 3 columns]

In [16]:
# merge df_df_df_industry_ret and df_5d_ret_long on industry
df_5d_ret_long = df_5d_ret_long.merge(df_industry_5d_ret, on=['date', 'industry'], how='left')
df_5d_ret_long

              date    ticker    5d_ret industry  industry_5d_ret
0       2004-01-09  0111145D -0.653777      NaN              NaN
1       2004-01-09  0202445Q -0.468735      NaN              NaN
2       2004-01-09  0203524D  3.066892      NaN              NaN
3       2004-01-09  0226226D -0.899135      NaN              NaN
4       2004-01-09  0544749D  4.307232      NaN              NaN
...            ...       ...       ...      ...              ...
5330915 2025-12-31       YUM -1.620455   253010        -1.299014
5330916 2025-12-31       ZBH  0.858266   351010        -0.619273
5330917 2025-12-31      ZBRA -1.236315   452030        -1.092482
5330918 2025-12-31      ZION       NaN   401010        -1.567176
5330919 2025-12-31       ZTS  1.389272   352020         0.704949

[5330920 rows x 5 columns]

In [17]:
# demean the variable by industry mean
df_5d_ret_long['5d_ret_minus_industry'] = df_5d_ret_long['5d_ret'] - df_5d_ret_long['industry_5d_ret']
df_5d_ret_long

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry
0,2004-01-09,0111145D,-0.653777,NaN,NaN,NaN
1,2004-01-09,0202445Q,-0.468735,NaN,NaN,NaN
2,2004-01-09,0203524D,3.066892,NaN,NaN,NaN
3,2004-01-09,0226226D,-0.899135,NaN,NaN,NaN
4,2004-01-09,0544749D,4.307232,NaN,NaN,NaN
...,...,...,...,...,...,...
5330915,2025-12-31,YUM,-1.620455,253010,-1.299014,-0.321441
5330916,2025-12-31,ZBH,0.858266,351010,-0.619273,1.477540
5330917,2025-12-31,ZBRA,-1.236315,452030,-1.092482,-0.143833
5330918,2025-12-31,ZION,NaN,401010,-1.567176,NaN
5330919,2025-12-31,ZTS,1.389272,352020,0.704949,0.684322

In [18]:
# create a mask with same size as df_log_return
df_log_return.columns = df_log_return.columns.str.strip()

mask = pd.DataFrame(
    False,
    index=df_log_return.index,
    columns=df_log_return.columns
)

for year, tickers in univ_dict.items():
    year_rows = df_log_return.index.year == year
    valid_cols = [t for t in tickers if t in df_log_return.columns]
    mask.loc[year_rows, valid_cols] = True

# apply mask on df_log_return, assign np.nan to values not in the universe
df_log_return_filtered = df_log_return.where(mask,np.nan)

# convert daily return into long format
df_log_return_long = (
    df_log_return_filtered
    .stack(dropna=False)
    .reset_index()
)

df_log_return_long.columns = ['date', 'ticker', 'log_return']

# merge daily return with industry
df_log_return_long = df_log_return_long.merge(df_tickers[['ticker', 'industry']], on='ticker', how='left')

# calculate the industry average return
df_industry_ret = (
    df_log_return_long
    .dropna(subset=['industry']) 
    .groupby(['date', 'industry'])['log_return']
    .mean()
    .reset_index()
)
df_industry_ret.rename(columns={'log_return': 'industry_log_return'}, inplace=True)

# merge df_industry_ret and df_log_return_long on industry
df_log_return_long = df_log_return_long.merge(df_industry_ret, on=['date', 'industry'], how='left')

# demean the daily return by industry mean
df_log_return_long['log_ret_minus_industry'] = df_log_return_long['log_return'] - df_log_return_long['industry_log_return']
df_log_return_long

,date,ticker,log_return,industry,industry_log_return,log_ret_minus_industry
0,2004-01-02,0111145D,0.000000,NaN,NaN,NaN
1,2004-01-02,0202445Q,0.000000,NaN,NaN,NaN
2,2004-01-02,0203524D,0.000000,NaN,NaN,NaN
3,2004-01-02,0226226D,0.000000,NaN,NaN,NaN
4,2004-01-02,0544749D,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...
5335735,2025-12-31,YUM,-0.005932,253010,-0.007299,0.001368
5335736,2025-12-31,ZBH,-0.009629,351010,-0.008030,-0.001599
5335737,2025-12-31,ZBRA,-0.016015,452030,-0.013802,-0.002212
5335738,2025-12-31,ZION,NaN,401010,-0.007451,NaN
5335739,2025-12-31,ZTS,-0.004678,352020,-0.004652,-0.000026

In [19]:
# merge df_log_return_long and df_5d_ret_long on ticker and date
df_final = df_5d_ret_long.merge(df_log_return_long[['date', 'ticker','log_return', 'log_ret_minus_industry']], on=['date', 'ticker'], how='left')
df_final.sort_values(by=['date', 'ticker'], inplace=True)
df_final

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry,log_return,log_ret_minus_industry
0,2004-01-09,0111145D,-0.653777,NaN,NaN,NaN,0.005975,NaN
1,2004-01-09,0202445Q,-0.468735,NaN,NaN,NaN,-0.020629,NaN
2,2004-01-09,0203524D,3.066892,NaN,NaN,NaN,-0.008367,NaN
3,2004-01-09,0226226D,-0.899135,NaN,NaN,NaN,0.023077,NaN
4,2004-01-09,0544749D,4.307232,NaN,NaN,NaN,0.008320,NaN
...,...,...,...,...,...,...,...,...
5330915,2025-12-31,YUM,-1.620455,253010,-1.299014,-0.321441,-0.005932,0.001368
5330916,2025-12-31,ZBH,0.858266,351010,-0.619273,1.477540,-0.009629,-0.001599
5330917,2025-12-31,ZBRA,-1.236315,452030,-1.092482,-0.143833,-0.016015,-0.002212
5330918,2025-12-31,ZION,NaN,401010,-1.567176,NaN,NaN,NaN
5330919,2025-12-31,ZTS,1.389272,352020,0.704949,0.684322,-0.004678,-0.000026

In [20]:
df_final['log_ret_minus_industry_plus_1'] = (
    df_final
    .groupby('ticker')['log_ret_minus_industry']
    .shift(-1)
)
df_final

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry,log_return,log_ret_minus_industry,log_ret_minus_industry_plus_1
0,2004-01-09,0111145D,-0.653777,NaN,NaN,NaN,0.005975,NaN,NaN
1,2004-01-09,0202445Q,-0.468735,NaN,NaN,NaN,-0.020629,NaN,NaN
2,2004-01-09,0203524D,3.066892,NaN,NaN,NaN,-0.008367,NaN,NaN
3,2004-01-09,0226226D,-0.899135,NaN,NaN,NaN,0.023077,NaN,NaN
4,2004-01-09,0544749D,4.307232,NaN,NaN,NaN,0.008320,NaN,NaN
...,...,...,...,...,...,...,...,...,...
5330915,2025-12-31,YUM,-1.620455,253010,-1.299014,-0.321441,-0.005932,0.001368,NaN
5330916,2025-12-31,ZBH,0.858266,351010,-0.619273,1.477540,-0.009629,-0.001599,NaN
5330917,2025-12-31,ZBRA,-1.236315,452030,-1.092482,-0.143833,-0.016015,-0.002212,NaN
5330918,2025-12-31,ZION,NaN,401010,-1.567176,NaN,NaN,NaN,NaN
5330919,2025-12-31,ZTS,1.389272,352020,0.704949,0.684322,-0.004678,-0.000026,NaN

In [21]:
# calculate beta
df_reg = df_final.dropna(subset=['log_ret_minus_industry_plus_1', '5d_ret_minus_industry'])

beta_series = (
    df_reg
    .groupby('date')
    .apply(lambda x: 
        (x['log_ret_minus_industry_plus_1'] * x['5d_ret_minus_industry']).sum()
        /
        (x['5d_ret_minus_industry']**2).sum() if (x['5d_ret_minus_industry']**2).sum() != 0 else np.nan
    )
)
beta_series

date
2004-01-09   -0.000072
2004-01-12    0.000328
2004-01-13   -0.000061
2004-01-14   -0.000277
2004-01-15    0.000786
                ...
2025-12-23   -0.000533
2025-12-24    0.000018
2025-12-26   -0.000353
2025-12-29    0.000240
2025-12-30    0.000826
Length: 5529, dtype: float64

In [22]:
# covert beta series into beta dataframe
beta_series = beta_series.reset_index()
beta_series.columns = ['date', 'beta']
beta_series

           date      beta
0    2004-01-09 -0.000072
1    2004-01-12  0.000328
2    2004-01-13 -0.000061
3    2004-01-14 -0.000277
4    2004-01-15  0.000786
...         ...       ...
5524 2025-12-23 -0.000533
5525 2025-12-24  0.000018
5526 2025-12-26 -0.000353
5527 2025-12-29  0.000240
5528 2025-12-30  0.000826

[5529 rows x 2 columns]

In [23]:
# calculate mean, std, number, t-stats for beta annually
beta_series['year'] = beta_series['date'].dt.year
yearly_stats = (
    beta_series
    .groupby('year')['beta']
    .agg(['mean', 'std', 'count'])
    .reset_index()
)
yearly_stats['t_stat'] = (yearly_stats['mean'] / yearly_stats['std']) * np.sqrt(yearly_stats['count'])
yearly_stats

    year      mean       std  count    t_stat
0   2004 -0.000136  0.000623    247 -3.434941
1   2005 -0.000133  0.000549    252 -3.845856
2   2006 -0.000160  0.000576    251 -4.401218
3   2007 -0.000081  0.000901    251 -1.422194
4   2008 -0.000497  0.003370    253 -2.348262
5   2009 -0.000137  0.002006    252 -1.086134
6   2010 -0.000057  0.000763    252 -1.195891
7   2011 -0.000176  0.001293    252 -2.164281
8   2012  0.000022  0.000676    250  0.511471
9   2013 -0.000065  0.000562    252 -1.842169
10  2014 -0.000025  0.000642    252 -0.624152
11  2015 -0.000005  0.000893    252 -0.097222
12  2016 -0.000070  0.001048    252 -1.055238
13  2017 -0.000043  0.000593    251 -1.155244
14  2018  0.000028  0.000935    251  0.472556
15  2019  0.000090  0.001160    252  1.227006
16  2020 -0.000375  0.003804    253 -1.568538
17  2021  0.000015  0.001479    252  0.161380
18  2022 -0.000013  0.001790    251 -0.119097
19  2023 -0.000173  0.001740    250 -1.575897
20  2024 -0.000104  0.000878    252 -1.883139
21  2025  0.000003  0.001411    249  0.037566

partB

In [24]:
# calculate beta bar
beta_bar = {}
for y in range(2006, 2025): #2006-2024
    start = max(2004, y - 5)
    end = y - 1

    window = beta_series.loc[
        (beta_series['year'] >= start) & (beta_series['year'] <= end),
        'beta'
    ]

    beta_bar[y] = window.mean()   # 直接对“日度beta”求均值（自动忽略NaN）

df_beta_bar = pd.Series(beta_bar, name='beta_bar').reset_index()
df_beta_bar.columns = ['year', 'beta_bar']
df_beta_bar

    year      beta_bar
0   2006 -1.345416e-04
1   2007 -1.430436e-04
2   2008 -1.274627e-04
3   2009 -2.021109e-04
4   2010 -2.020834e-04
5   2011 -1.869645e-04
6   2012 -1.902097e-04
7   2013 -1.698888e-04
8   2014 -8.305165e-05
9   2015 -6.060993e-05
10  2016 -5.019070e-05
11  2017 -2.882728e-05
12  2018 -4.176072e-05
13  2019 -2.315456e-05
14  2020 -1.418075e-07
15  2021 -7.442227e-05
16  2022 -5.747505e-05
17  2023 -5.154340e-05
18  2024 -9.162150e-05

In [25]:
# merge df_final and df_beta_bar on year
df_final['year'] = df_final['date'].dt.year
df_final_beta = pd.merge(df_final, df_beta_bar, on='year', how='left')
df_final_beta.dropna(subset=['beta_bar'], inplace=True)

df_final_beta

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry,log_return,log_ret_minus_industry,log_ret_minus_industry_plus_1,year,beta_bar
481036,2006-01-03,0111145D,1.820895,NaN,NaN,NaN,0.044080,NaN,NaN,2006,-0.000135
481037,2006-01-03,0202445Q,0.604735,NaN,NaN,NaN,0.020088,NaN,NaN,2006,-0.000135
481038,2006-01-03,0203524D,-0.293967,NaN,NaN,NaN,0.036657,NaN,NaN,2006,-0.000135
481039,2006-01-03,0226226D,2.451989,NaN,NaN,NaN,0.024321,NaN,NaN,2006,-0.000135
481040,2006-01-03,0544749D,1.405995,NaN,NaN,NaN,0.036948,NaN,NaN,2006,-0.000135
...,...,...,...,...,...,...,...,...,...,...,...
5089915,2024-12-31,YUM,0.224810,253010,-0.476562,0.701373,0.004781,0.003385,0.001233,2024,-0.000092
5089916,2024-12-31,ZBH,-0.974400,351010,-0.590139,-0.384261,0.002179,0.000853,-0.007764,2024,-0.000092
5089917,2024-12-31,ZBRA,-0.768009,452030,-0.700073,-0.067937,0.006155,0.005099,0.004754,2024,-0.000092
5089918,2024-12-31,ZION,-0.144845,401010,-0.086945,-0.057900,-0.001288,-0.001367,NaN,2024,-0.000092
5089919,2024-12-31,ZTS,-0.722500,352020,-0.635544,-0.086955,0.004244,-0.000836,-0.002430,2024,-0.000092

In [26]:
# calculate expected return
df_final_beta['expected ret'] = df_final_beta['beta_bar'] * df_final_beta['5d_ret_minus_industry']
df_final_beta

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry,log_return,log_ret_minus_industry,log_ret_minus_industry_plus_1,year,beta_bar,expected ret
481036,2006-01-03,0111145D,1.820895,NaN,NaN,NaN,0.044080,NaN,NaN,2006,-0.000135,NaN
481037,2006-01-03,0202445Q,0.604735,NaN,NaN,NaN,0.020088,NaN,NaN,2006,-0.000135,NaN
481038,2006-01-03,0203524D,-0.293967,NaN,NaN,NaN,0.036657,NaN,NaN,2006,-0.000135,NaN
481039,2006-01-03,0226226D,2.451989,NaN,NaN,NaN,0.024321,NaN,NaN,2006,-0.000135,NaN
481040,2006-01-03,0544749D,1.405995,NaN,NaN,NaN,0.036948,NaN,NaN,2006,-0.000135,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5089915,2024-12-31,YUM,0.224810,253010,-0.476562,0.701373,0.004781,0.003385,0.001233,2024,-0.000092,-0.000064
5089916,2024-12-31,ZBH,-0.974400,351010,-0.590139,-0.384261,0.002179,0.000853,-0.007764,2024,-0.000092,0.000035
5089917,2024-12-31,ZBRA,-0.768009,452030,-0.700073,-0.067937,0.006155,0.005099,0.004754,2024,-0.000092,0.000006
5089918,2024-12-31,ZION,-0.144845,401010,-0.086945,-0.057900,-0.001288,-0.001367,NaN,2024,-0.000092,0.000005
5089919,2024-12-31,ZTS,-0.722500,352020,-0.635544,-0.086955,0.004244,-0.000836,-0.002430,2024,-0.000092,0.000008

In [27]:
# get signal
df_signal = df_final_beta.dropna(subset=['expected ret']).copy()
# calculate daily rank
df_signal['pct_rank'] = (
    df_signal
    .groupby('date')['expected ret']
    .rank(pct=True)
)
# create signal based on daily rank
df_signal['signal'] = 0

df_signal.loc[df_signal['pct_rank'] >= 0.8, 'signal'] = 1
df_signal.loc[df_signal['pct_rank'] <= 0.2, 'signal'] = -1

# convert log return to simple return
df_signal['simple return'] = np.exp(df_signal['log_return']) - 1

df_signal

,date,ticker,5d_ret,industry,industry_5d_ret,5d_ret_minus_industry,log_return,log_ret_minus_industry,log_ret_minus_industry_plus_1,year,beta_bar,expected ret,pct_rank,signal,simple return
481045,2006-01-03,0910150D,3.599892,253010,0.138429,3.461463,0.014821,0.008875,-0.016252,2006,-0.000135,-0.000466,0.005450,-1,0.014931
481055,2006-01-03,1284849D,0.047181,352020,-0.043515,0.090696,0.010686,-0.004091,0.003570,2006,-0.000135,-0.000012,0.474114,0,0.010744
481064,2006-01-03,1500785D,0.736812,551030,0.247299,0.489512,0.020165,0.003391,0.006726,2006,-0.000135,-0.000066,0.332425,0,0.020369
481065,2006-01-03,1518855D,0.422717,502030,0.391362,0.031355,0.043208,0.018917,0.011197,2006,-0.000135,-0.000004,0.512262,0,0.044155
481066,2006-01-03,1519128D,-0.456631,451030,-0.147437,-0.309193,0.038272,0.021842,-0.007787,2006,-0.000135,0.000042,0.640327,0,0.039014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5089915,2024-12-31,YUM,0.224810,253010,-0.476562,0.701373,0.004781,0.003385,0.001233,2024,-0.000092,-0.000064,0.147705,-1,0.004793
5089916,2024-12-31,ZBH,-0.974400,351010,-0.590139,-0.384261,0.002179,0.000853,-0.007764,2024,-0.000092,0.000035,0.722555,0,0.002182
5089917,2024-12-31,ZBRA,-0.768009,452030,-0.700073,-0.067937,0.006155,0.005099,0.004754,2024,-0.000092,0.000006,0.562874,0,0.006174
5089918,2024-12-31,ZION,-0.144845,401010,-0.086945,-0.057900,-0.001288,-0.001367,NaN,2024,-0.000092,0.000005,0.560878,0,-0.001287
5089919,2024-12-31,ZTS,-0.722500,352020,-0.635544,-0.086955,0.004244,-0.000836,-0.002430,2024,-0.000092,0.000008,0.566866,0,0.004253

In [28]:
# calculate portfolio return
df_signal['signal_plus_1'] = df_signal.groupby('ticker')['signal'].shift(1) #signal向下移动一行
df_signal.dropna(subset=['signal_plus_1'], inplace=True)

In [29]:
def calc_port_ret(x):
    long_mask = (x['signal_plus_1'] == 1) & x['log_return'].notna()
    short_mask = (x['signal_plus_1'] == -1) & x['log_return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:   
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'log_return'].sum()
    short_sum = x.loc[short_mask, 'log_return'].sum()

    port_ret = (long_sum - short_sum) / Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port = (
    df_signal.groupby('date', as_index=False)
      .apply(calc_port_ret)
      .reset_index(drop=True)
)

daily_port

           date     Nl     Ns  port_ret
0    2006-01-04   74.0   73.0  0.003024
1    2006-01-05   74.0   73.0  0.001250
2    2006-01-06   74.0   73.0  0.002781
3    2006-01-09   74.0   73.0 -0.003618
4    2006-01-10   74.0   73.0  0.001711
...         ...    ...    ...       ...
4775 2024-12-24  101.0  100.0  0.001868
4776 2024-12-26  101.0  100.0 -0.000422
4777 2024-12-27  101.0  100.0  0.001046
4778 2024-12-30  101.0  100.0 -0.001506
4779 2024-12-31  101.0  100.0  0.000015

[4780 rows x 4 columns]

In [30]:
# calculate total annual return and annual return volatility for portfolio
daily_port['year'] = daily_port['date'].dt.year
annual_stats = (
    daily_port
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.190455           0.041244      4.617770
1   2007             0.088001           0.065845      1.336490
2   2008             0.391532           0.174598      2.242474
3   2009             0.109670           0.112984      0.970663
4   2010             0.055799           0.045738      1.219981
5   2011             0.130569           0.062524      2.088287
6   2012             0.024490           0.048039      0.509802
7   2013             0.040373           0.037840      1.066937
8   2014             0.033948           0.042939      0.790602
9   2015             0.018476           0.054238      0.340644
10  2016             0.029181           0.065333      0.446653
11  2017             0.071588           0.042162      1.697940
12  2018            -0.052182           0.052882     -0.986755
13  2019            -0.045562           0.069855     -0.652238
14  2020             0.305517           0.227956      1.340246
15  2021             0.030800           0.097973      0.314375
16  2022             0.091288           0.105011      0.869325
17  2023             0.086310           0.101511      0.850247
18  2024             0.129462           0.065771      1.968373

In [31]:
#2. portfolio return based on simple return
def calc_port_ret_simple(x):
    long_mask = (x['signal_plus_1'] == 1) & x['simple return'].notna()
    short_mask = (x['signal_plus_1'] == -1) & x['simple return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:   
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'simple return'].sum()
    short_sum = x.loc[short_mask, 'simple return'].sum()

    port_ret = (long_sum - short_sum) / Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port_simple = (
    df_signal.groupby('date', as_index=False)
      .apply(calc_port_ret_simple)
      .reset_index(drop=True)
)   

# calculate total annual return and annual return volatility for portfolio
daily_port_simple['year'] = daily_port_simple['date'].dt.year
annual_stats = (
    daily_port_simple
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.193411           0.041480      4.662778
1   2007             0.095204           0.065689      1.449316
2   2008             0.489273           0.177393      2.758131
3   2009             0.116485           0.113923      1.022486
4   2010             0.057587           0.046140      1.248106
5   2011             0.144049           0.062353      2.310227
6   2012             0.031025           0.048323      0.642034
7   2013             0.044356           0.037989      1.167620
8   2014             0.037012           0.042798      0.864800
9   2015             0.026472           0.054244      0.488024
10  2016             0.033925           0.065404      0.518700
11  2017             0.077183           0.042068      1.834703
12  2018            -0.045347           0.052663     -0.861086
13  2019            -0.032402           0.069320     -0.467427
14  2020             0.359413           0.223838      1.605686
15  2021             0.031828           0.098009      0.324747
16  2022             0.110289           0.104589      1.054503
17  2023             0.190540           0.119254      1.597760
18  2024             0.128885           0.065405      1.970569

Part C

In [32]:
#trading cost
COST_PER_TRADE = 0.0005

df_signal['pos'] = df_signal['signal_plus_1']
df_signal['pos_next'] = df_signal['signal']
df_signal['trade'] = (df_signal['pos'] - df_signal['pos_next']).abs()

In [33]:
#1. portfolio return based onlog return
def calc_port_ret_cost(x):
    long_mask = (x['signal_plus_1'] == 1) & x['log_return'].notna()
    short_mask = (x['signal_plus_1'] == -1) & x['log_return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:   
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'log_return'].sum()
    short_sum = x.loc[short_mask, 'log_return'].sum()
    trade_sum = x['trade'].sum()

    port_ret = (long_sum - short_sum) / Nl - trade_sum*COST_PER_TRADE/Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port_cost = (
    df_signal.groupby('date', as_index=False)
      .apply(calc_port_ret_cost)
      .reset_index(drop=True)
)   

# calculate total annual return and annual return volatility for portfolio
daily_port_cost['year'] = daily_port_cost['date'].dt.year
annual_stats = (
    daily_port_cost
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.015117           0.040844      0.370118
1   2007            -0.084480           0.065430     -1.291155
2   2008             0.212849           0.174141      1.222284
3   2009            -0.063418           0.112534     -0.563547
4   2010            -0.115639           0.045462     -2.543630
5   2011            -0.044533           0.062145     -0.716598
6   2012            -0.148896           0.047615     -3.127101
7   2013            -0.132584           0.037505     -3.535121
8   2014            -0.139809           0.042672     -3.276374
9   2015            -0.153106           0.053791     -2.846284
10  2016            -0.141978           0.064888     -2.188044
11  2017            -0.098731           0.041832     -2.360203
12  2018            -0.220858           0.052333     -4.220228
13  2019            -0.216470           0.069259     -3.125514
14  2020             0.127672           0.227349      0.561568
15  2021            -0.139785           0.097511     -1.433526
16  2022            -0.078906           0.104451     -0.755435
17  2023            -0.081888           0.101090     -0.810053
18  2024            -0.042569           0.065441     -0.650487

In [34]:
#2. portfolio return based on simple return
def calc_port_ret_simple_cost(x):
    long_mask = (x['signal_plus_1'] == 1) & x['simple return'].notna()
    short_mask = (x['signal_plus_1'] == -1) & x['simple return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:   
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'simple return'].sum()
    short_sum = x.loc[short_mask, 'simple return'].sum()
    trade_sum = x['trade'].sum()

    port_ret = (long_sum - short_sum) / Nl -trade_sum*COST_PER_TRADE/Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port_simple_cost = (
    df_signal.groupby('date', as_index=False)
      .apply(calc_port_ret_simple_cost)
      .reset_index(drop=True)
)   

# calculate total annual return and annual return volatility for portfolio
daily_port_simple_cost['year'] = daily_port_simple_cost['date'].dt.year
annual_stats = (
    daily_port_simple_cost
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.018073           0.041080      0.439945
1   2007            -0.077277           0.065279     -1.183796
2   2008             0.310591           0.176938      1.755364
3   2009            -0.056603           0.113471     -0.498836
4   2010            -0.113851           0.045862     -2.482475
5   2011            -0.031053           0.061972     -0.501077
6   2012            -0.142361           0.047900     -2.972048
7   2013            -0.128601           0.037650     -3.415696
8   2014            -0.136745           0.042532     -3.215097
9   2015            -0.145109           0.053802     -2.697080
10  2016            -0.137235           0.064962     -2.112547
11  2017            -0.093136           0.041735     -2.231594
12  2018            -0.214023           0.052112     -4.106996
13  2019            -0.203310           0.068721     -2.958471
14  2020             0.181569           0.223230      0.813371
15  2021            -0.138757           0.097550     -1.422418
16  2022            -0.059905           0.104028     -0.575852
17  2023             0.022342           0.118902      0.187902
18  2024            -0.043146           0.065071     -0.663062

Part D

In [35]:
df_signal.drop(columns=['industry','5d_ret','industry_5d_ret','year'],inplace=True)

In [36]:
#normalize expected return
df_signal['w0'] = (
    df_signal.groupby('date')['expected ret']
      .transform(lambda x: 0.5 * np.abs(x).sum())
)

df_signal['normalize ret'] = df_signal['expected ret'] / df_signal['w0']
df_signal.drop(columns='w0',inplace=True)
df_signal

,date,ticker,5d_ret_minus_industry,log_return,log_ret_minus_industry,log_ret_minus_industry_plus_1,beta_bar,expected ret,pct_rank,signal,simple return,signal_plus_1,pos,pos_next,trade,normalize ret
482009,2006-01-04,0910150D,1.758916,-0.009856,-0.016252,0.004931,-0.000135,-0.000237,0.108992,-1,-0.009808,-1.0,-1.0,-1,0.0,-0.008337
482019,2006-01-04,1284849D,1.042392,0.010756,0.003570,-0.014611,-0.000135,-0.000140,0.231608,0,0.010814,0.0,0.0,0,0.0,-0.004941
482028,2006-01-04,1500785D,1.215280,0.004551,0.006726,-0.005217,-0.000135,-0.000164,0.190736,-1,0.004561,0.0,0.0,-1,1.0,-0.005760
482029,2006-01-04,1518855D,0.863916,0.001466,0.011197,-0.010333,-0.000135,-0.000116,0.280654,0,0.001467,0.0,0.0,0,0.0,-0.004095
482030,2006-01-04,1519128D,0.147146,0.002142,-0.007787,0.005766,-0.000135,-0.000020,0.455041,0,0.002144,0.0,0.0,0,0.0,-0.000697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5089915,2024-12-31,YUM,0.701373,0.004781,0.003385,0.001233,-0.000092,-0.000064,0.147705,-1,0.004793,-1.0,-1.0,-1,0.0,-0.005134
5089916,2024-12-31,ZBH,-0.384261,0.002179,0.000853,-0.007764,-0.000092,0.000035,0.722555,0,0.002182,1.0,1.0,0,1.0,0.002813
5089917,2024-12-31,ZBRA,-0.067937,0.006155,0.005099,0.004754,-0.000092,0.000006,0.562874,0,0.006174,1.0,1.0,0,1.0,0.000497
5089918,2024-12-31,ZION,-0.057900,-0.001288,-0.001367,NaN,-0.000092,0.000005,0.560878,0,-0.001287,0.0,0.0,0,0.0,0.000424
5089919,2024-12-31,ZTS,-0.086955,0.004244,-0.000836,-0.002430,-0.000092,0.000008,0.566866,0,0.004253,1.0,1.0,0,1.0,0.000637

In [51]:
df_d = df_signal[['date','ticker','log_return','simple return','pos','normalize ret']].copy()
df_d

              date    ticker  log_return  simple return  pos  normalize ret
482009  2006-01-04  0910150D   -0.009856      -0.009808 -1.0      -0.008337
482019  2006-01-04  1284849D    0.010756       0.010814  0.0      -0.004941
482028  2006-01-04  1500785D    0.004551       0.004561  0.0      -0.005760
482029  2006-01-04  1518855D    0.001466       0.001467  0.0      -0.004095
482030  2006-01-04  1519128D    0.002142       0.002144  0.0      -0.000697
...            ...       ...         ...            ...  ...            ...
5089915 2024-12-31       YUM    0.004781       0.004793 -1.0      -0.005134
5089916 2024-12-31       ZBH    0.002179       0.002182  1.0       0.002813
5089917 2024-12-31      ZBRA    0.006155       0.006174  1.0       0.000497
5089918 2024-12-31      ZION   -0.001288      -0.001287  0.0       0.000424
5089919 2024-12-31       ZTS    0.004244       0.004253  1.0       0.000637

[2247838 rows x 6 columns]

In [52]:
gamma = 1
dates = df_d['date'].drop_duplicates().tolist()

# daily position list
out_list = []

# ticker -> p in {-1,0,1}
df_target_date = df_d[df_d['date'] == '2006-01-04']
pos_prev = dict(zip(df_target_date['ticker'], df_target_date['pos'])) # pos at t, calculated by previous signal

In [53]:
for dt in dates: 
    d = df_d[df_d['date'] == dt].copy()

    #  universe (ticker with normalize ret)
    tickers = d['ticker'].tolist()
    N = len(tickers)

    # sigma and hurdle
    sigma = d['normalize ret'].std()
    h = gamma * sigma

    # append today's position to today's df
    d['p_prev'] = d['ticker'].map(pos_prev).fillna(0).astype(int)

    # construct x and y
    # x: long score
    d['x'] = d['normalize ret']
    d.loc[d['p_prev'] == 0,  'x'] = d.loc[d['p_prev'] == 0,  'normalize ret'] - h
    d.loc[d['p_prev'] == -1, 'x'] = d.loc[d['p_prev'] == -1, 'normalize ret'] - 2*h

    # y: short score
    d['y'] = -d['normalize ret']
    d.loc[d['p_prev'] == 1,  'y'] = -d.loc[d['p_prev'] == 1,  'normalize ret'] - 2*h
    d.loc[d['p_prev'] == 0,  'y'] = -d.loc[d['p_prev'] == 0,  'normalize ret'] - h

    # number of ticker to long
    K = int(np.floor(0.2 * N))
    K = max(K, 1)

    # long：x, the largest K number of return 
    long_names = d.nlargest(K, 'x')['ticker'].tolist()

    # short：y, the largest K number of return, avoid overlapping with x
    d_short_pool = d[~d['ticker'].isin(long_names)].copy()
    short_names = d_short_pool.nlargest(K, 'y')['ticker'].tolist()

    # new position for tomorrow
    d['pos'] = 0
    d.loc[d['ticker'].isin(long_names), 'pos'] = 1
    d.loc[d['ticker'].isin(short_names), 'pos'] = -1

    out_list.append(d[['date','ticker','p_prev','pos']])

    # update pos_prev for the next day
    for tkr, pnew in zip(d['ticker'], d['pos']):
        pos_prev[tkr] = int(pnew)

df_pos = pd.concat(out_list, ignore_index=True)
df_pos

              date    ticker  p_prev  pos
0       2006-01-04  0910150D      -1   -1
1       2006-01-04  1284849D       0    0
2       2006-01-04  1500785D       0    0
3       2006-01-04  1518855D       0    0
4       2006-01-04  1519128D       0    0
...            ...       ...     ...  ...
2247833 2024-12-31       YUM      -1   -1
2247834 2024-12-31       ZBH       0    0
2247835 2024-12-31      ZBRA       1    1
2247836 2024-12-31      ZION       0    0
2247837 2024-12-31       ZTS       1    1

[2247838 rows x 4 columns]

In [54]:
df_pos['trade'] = (df_pos['p_prev']-df_pos['pos']).abs()
df_pos

              date    ticker  p_prev  pos  trade
0       2006-01-04  0910150D      -1   -1      0
1       2006-01-04  1284849D       0    0      0
2       2006-01-04  1500785D       0    0      0
3       2006-01-04  1518855D       0    0      0
4       2006-01-04  1519128D       0    0      0
...            ...       ...     ...  ...    ...
2247833 2024-12-31       YUM      -1   -1      0
2247834 2024-12-31       ZBH       0    0      0
2247835 2024-12-31      ZBRA       1    1      0
2247836 2024-12-31      ZION       0    0      0
2247837 2024-12-31       ZTS       1    1      0

[2247838 rows x 5 columns]

In [55]:
df_d.drop(columns='pos',inplace=True)
df_d = df_d.merge(df_pos[['date','ticker','p_prev','trade']],on=['date','ticker'],how='left')
df_d

,date,ticker,log_return,simple return,normalize ret,p_prev,trade
0,2006-01-04,0910150D,-0.009856,-0.009808,-0.008337,-1,0
1,2006-01-04,1284849D,0.010756,0.010814,-0.004941,0,0
2,2006-01-04,1500785D,0.004551,0.004561,-0.005760,0,0
3,2006-01-04,1518855D,0.001466,0.001467,-0.004095,0,0
4,2006-01-04,1519128D,0.002142,0.002144,-0.000697,0,0
...,...,...,...,...,...,...,...
2247833,2024-12-31,YUM,0.004781,0.004793,-0.005134,-1,0
2247834,2024-12-31,ZBH,0.002179,0.002182,0.002813,0,0
2247835,2024-12-31,ZBRA,0.006155,0.006174,0.000497,1,0
2247836,2024-12-31,ZION,-0.001288,-0.001287,0.000424,0,0
2247837,2024-12-31,ZTS,0.004244,0.004253,0.000637,1,0

In [56]:
#calculate porfolio return based on log return
def calc_port_ret_cost(x):
    long_mask = (x['p_prev'] == 1) & x['log_return'].notna()
    short_mask = (x['p_prev'] == -1) & x['log_return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:  
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'log_return'].sum()
    short_sum = x.loc[short_mask, 'log_return'].sum()
    trade_sum = x['trade'].sum()

    port_ret = (long_sum - short_sum) / Nl -trade_sum*COST_PER_TRADE/Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port_cost = (
    df_d.groupby('date', as_index=False)
      .apply(calc_port_ret_cost)
      .reset_index(drop=True)
)   

# calculate total annual return and annual return volatility for portfolio
daily_port_cost['year'] = daily_port_cost['date'].dt.year
annual_stats = (
    daily_port_cost
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.024676           0.042893      0.575287
1   2007            -0.006320           0.063554     -0.099446
2   2008             0.253887           0.169837      1.494880
3   2009            -0.007131           0.120290     -0.059280
4   2010            -0.015711           0.044432     -0.353589
5   2011             0.005623           0.061251      0.091807
6   2012            -0.083658           0.046444     -1.801285
7   2013            -0.018278           0.037594     -0.486192
8   2014            -0.061854           0.044675     -1.384544
9   2015            -0.103473           0.054844     -1.886685
10  2016             0.013932           0.062619      0.222480
11  2017            -0.066467           0.044004     -1.510474
12  2018            -0.157152           0.055962     -2.808190
13  2019            -0.087133           0.066599     -1.308323
14  2020             0.212025           0.220131      0.963177
15  2021            -0.081936           0.093646     -0.874957
16  2022            -0.023608           0.097941     -0.241040
17  2023            -0.014820           0.096659     -0.153321
18  2024            -0.010162           0.063058     -0.161148

In [57]:
# calculate porfolio return based on simple return
def calc_port_ret_cost(x):
    long_mask = (x['p_prev'] == 1) & x['simple return'].notna()
    short_mask = (x['p_prev'] == -1) & x['simple return'].notna()

    Nl = long_mask.sum()
    Ns = short_mask.sum()

    if Nl == 0:   
        return pd.Series({'Nl': 0, 'Ns': Ns, 'port_ret': np.nan})

    long_sum = x.loc[long_mask, 'simple return'].sum()
    short_sum = x.loc[short_mask, 'simple return'].sum()
    trade_sum = x['trade'].sum()

    port_ret = (long_sum - short_sum) / Nl - trade_sum*COST_PER_TRADE/Nl
    return pd.Series({'Nl': Nl, 'Ns': Ns, 'port_ret': port_ret})

daily_port_cost = (
    df_d.groupby('date', as_index=False)
      .apply(calc_port_ret_cost)
      .reset_index(drop=True)
)   

# calculate total annual return and annual return volatility
daily_port_cost['year'] = daily_port_cost['date'].dt.year
annual_stats = (
    daily_port_cost
    .groupby('year')['port_ret']
    .agg(['sum', 'std','mean','count'])
    .reset_index()
)
annual_stats.rename(columns={'sum': 'total annual return', 'std': 'return std', 'mean': 'annual mean return', 'count': 'number of trading days'}, inplace=True)
annual_stats['annual return vol'] = annual_stats['return std'] * np.sqrt(annual_stats['number of trading days'])
annual_stats['sharpe_ratio'] = (annual_stats['annual mean return'] / annual_stats['return std'])*np.sqrt(annual_stats['number of trading days'])   
annual_stats[['year', 'total annual return', 'annual return vol', 'sharpe_ratio']]

    year  total annual return  annual return vol  sharpe_ratio
0   2006             0.028573           0.043017      0.664211
1   2007             0.006358           0.063052      0.100833
2   2008             0.348394           0.170045      2.048834
3   2009             0.007776           0.120155      0.064719
4   2010            -0.012746           0.044924     -0.283734
5   2011             0.018390           0.061251      0.300245
6   2012            -0.078946           0.046585     -1.694652
7   2013            -0.013756           0.037841     -0.363531
8   2014            -0.056550           0.044556     -1.269174
9   2015            -0.097374           0.055102     -1.767153
10  2016             0.018744           0.062630      0.299283
11  2017            -0.061014           0.043968     -1.387699
12  2018            -0.148912           0.055867     -2.665468
13  2019            -0.073508           0.066593     -1.103833
14  2020             0.264532           0.218341      1.211557
15  2021            -0.080620           0.093582     -0.861490
16  2022            -0.005252           0.097855     -0.053672
17  2023             0.123926           0.115767      1.070482
18  2024            -0.009284           0.062683     -0.148113